In [1]:
from neural_lam.configs import get_constants
C = get_constants("nextgems")

In [2]:
print(C.get_grid_state_dim())

83


In [3]:
print(C.get_eval_plot_vars())

[ 3 16 29 42 55 68  7 20 33 46 59 72 10 23 36 49 62 75 78 79 80 81 82]


In [1]:
from neural_lam.configs import get_constants
C_ukesm = get_constants("ukesm")

In [8]:
import numpy as np
list = C_ukesm.get_eval_plot_vars()
print(np.sort(list))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 36 37 38 39 40 41]


In [9]:
print(np.sort(C_ukesm.get_eval_plot_vars_alt()))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 36 37 38 39 40 41]


In [9]:
import cftime
import create_global_forcing_stable as cgfs
import time
import numpy as np

from datetime import datetime, timedelta

# --- Gregorian Calendar ---
gregorian_start = np.datetime64('2025-01-01T00:00:00')
gregorian_end = np.datetime64('2025-12-31T23:59:59')

# --- 360-day Calendar ---
# Each month has 30 days, so year runs from Jan 1 to Dec 30
day_360_start = cftime.Datetime360Day(2025, 1, 1, 0, 0, 0)
day_360_end = cftime.Datetime360Day(2025, 12, 30, 23, 59, 59)


print(cgfs.get_year_progress(gregorian_start.astype("int64")))

epoch = cftime.Datetime360Day(1959, 1, 1, 0, 0, 0)
seconds_since_epoch = np.array(
    [(t - epoch).total_seconds() for t in [day_360_start]], dtype=np.float64
)
print(cgfs.get_year_progress(seconds_since_epoch))
print(cgfs.get_year_progress_ukesm(seconds_since_epoch)) 

print(cgfs.get_year_progress(gregorian_end.astype("int64")))

epoch = cftime.Datetime360Day(1959, 1, 1, 0, 0, 0)
seconds_since_epoch = np.array(
    [(t - epoch).total_seconds() for t in [day_360_end]], dtype=np.float64
)
print(cgfs.get_year_progress(seconds_since_epoch))
print(cgfs.get_year_progress_ukesm(seconds_since_epoch)) 
        

0.0018605463
[0.0527257]
[0.]
0.0011974203
[0.03837303]
[0.99999994]


In [17]:
for i in range(12):
    print(cgfs.get_year_progress(np.datetime64(f'2005-{i+1:02d}-01T00:00:00').astype("int64")))

0.0014328848
0.08630808
0.16296953
0.24784473
0.329982
0.41485718
0.49699447
0.58186966
0.6667448
0.7488821
0.83375734
0.9158946


In [19]:
days = []
for i in range(12):
    days.append(cftime.Datetime360Day(2015, i+1, 1, 0, 0, 0))

seconds_since_epoch = np.array(
    [(t - epoch).total_seconds() for t in days], dtype=np.float64
)

print(cgfs.get_year_progress(seconds_since_epoch))
print(cgfs.get_year_progress_ukesm(seconds_since_epoch)) 

[0.19625211 0.2783894  0.36052668 0.44266394 0.52480125 0.6069385
 0.68907577 0.77121305 0.85335034 0.9354876  0.01762491 0.09976219]
[0.         0.08333334 0.16666667 0.25       0.33333334 0.41666666
 0.5        0.5833333  0.6666667  0.75       0.8333333  0.9166667 ]
