In [1]:
from neural_lam.configs import get_constants
C = get_constants("nextgems")

In [2]:
print(C.get_grid_state_dim())

83


In [3]:
print(C.get_eval_plot_vars())

[ 3 16 29 42 55 68  7 20 33 46 59 72 10 23 36 49 62 75 78 79 80 81 82]


In [1]:
from neural_lam.configs import get_constants
C_ukesm = get_constants("ukesm")

In [8]:
import numpy as np
list = C_ukesm.get_eval_plot_vars()
print(np.sort(list))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 36 37 38 39 40 41]


In [9]:
print(np.sort(C_ukesm.get_eval_plot_vars_alt()))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 36 37 38 39 40 41]


In [ ]:
import cftime
import create_global_forcing_stable as cgfs
import time
import numpy as np

from datetime import datetime, timedelta

# --- Gregorian Calendar ---
gregorian_start = np.datetime64('2025-01-01T00:00:00')
gregorian_end = np.datetime64('2025-12-31T23:59:59')

# --- 360-day Calendar ---
# Each month has 30 days, so year runs from Jan 1 to Dec 30
day_360_start = datetime(2025, 1, 1, 0, 0, 0)
day_360_end = datetime(2025, 12, 30, 23, 59, 59)


print(cgfs.get_year_progress(gregorian_start.astype("int64")))

epoch = cftime.Datetime360Day(1959, 1, 1, 0, 0, 0)
seconds_since_epoch = np.array(
    [(t - epoch).total_seconds() for t in [day_360_start]], dtype=np.float64
)
print(cgfs.get_year_progress(seconds_since_epoch))
        
        

0.0018605463


TypeError: 
Cannot compute the time difference between dates with different calendars.
One of the datetime objects may have been converted to a native python
datetime instance.  Try using only_use_cftime_datetimes=True when creating the
datetime object.